name: Playwright Cucumber Tests

on:
  push:
    branches: [qa]
  pull_request:
    branches: [qa]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --verbose

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright + Cucumber Tests
        run: |
          npx cucumber-js web/features/**/*.feature \
            --require web/features/steps/**/*.ts \
            --require-module ts-node/register \
            --format json:reports/json/cucumber_report.json
      - uses: actions/upload-artifact@v4
        if: alway()
        with:
        name: playwright-report-ui
        path: playwright-report/
        retention-days: 30
